language: java
jdk:
  - openjdk8

services:
  - redis

env:
  global:
    - ORG_GRADLE_PROJECT_sonatypeUsername=xxx
    - ORG_GRADLE_PROJECT_sonatypePassword=xxx
    - USER_NAME=rqueue
    - REDIS_RUNNING=true
    - CI_ENV=true

cache:
  directories:
    - $HOME/.gradle

before_script:
  - mkdir 9000 9001 9002 9003 9004 9005
  - printf "port 9000 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9000/redis.conf
  - printf "port 9001 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9001/redis.conf
  - printf "port 9002 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9002/redis.conf
  - printf "port 9003 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9003/redis.conf
  - printf "port 9004 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9004/redis.conf
  - printf "port 9005 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9005/redis.conf
  - cd 9000 && redis-server ./redis.conf &
  - cd 9001 && redis-server ./redis.conf &
  - cd 9002 && redis-server ./redis.conf &
  - cd 9003 && redis-server ./redis.conf &
  - cd 9004 && redis-server ./redis.conf &
  - cd 9005 && redis-server ./redis.conf &
  - redis-cli --cluster create 127.0.0.1:9000 127.0.0.1:9001 127.0.0.1:9002 127.0.0.1:9003 127.0.0.1:9004 127.0.0.1:9005 --cluster-replicas 1 --cluster-yes
  - df -h
  - lscpu

jobs:
  include:
    - stage: spring-boot-2.1
      env:
        - SPRING_BOOT_VERSION=2.1.0.RELEASE
        - SPRING_VERSION=5.1.2.RELEASE
        - SPRING_DATA_VERSION=2.1.2.RELEASE
        - MICROMETER_VERSION=1.1.0
      script:
        - ./gradlew codeCoverageReport
    - stage: spring-boot-2.2
      env:
        - SPRING_BOOT_VERSION=2.2.0.RELEASE
        - SPRING_VERSION=5.2.0.RELEASE
        - SPRING_DATA_VERSION=2.2.0.RELEASE
        - MICROMETER_VERSION=1.3.2
      script:
        - ./gradlew codeCoverageReport


notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  - ./gradlew coveralls
